// Monster cards. Stats follow the classic TCG printings used in the anime duels
// this project recreates. `art` is a prompt seed for the cinema layer, never a
// bundled image -- no licensed artwork ships with this repo.

const m = (id, name, level, attribute, type, atk, def, art, extra = {}) => ({
  id, name, kind: "monster", level, attribute, type, atk, def, art, ...extra,
});

export const MONSTERS = {
  // -- Yugi -------------------------------------------------------------
  darkMagician: m("darkMagician", "Dark Magician", 7, "DARK", "Spellcaster", 2500, 2100,
    "a violet-robed sorcerer with a green staff, arcane runes spiralling around him"),
  darkMagicianGirl: m("darkMagicianGirl", "Dark Magician Girl", 6, "DARK", "Spellcaster", 2000, 1700,
    "a young blue-and-pink armoured sorceress with a spiral wand and blonde hair",
    { onSummonBuff: { perGraveyard: ["darkMagician"], atk: 300 } }),
  kuriboh: m("kuriboh", "Kuriboh", 1, "DARK", "Fiend", 300, 200,
    "a small round brown furry creature with huge green eyes and tiny clawed hands",
    { shieldFromHand: true }),
  celticGuardian: m("celticGuardian", "Celtic Guardian", 4, "EARTH", "Warrior", 1400, 1200,
    "a lithe blond elven swordsman in green and bronze armour"),
  beaverWarrior: m("beaverWarrior", "Beaver Warrior", 4, "EARTH", "Beast-Warrior", 1200, 1500,
    "an armoured beaver soldier with a short sword and round shield"),
  gaia: m("gaia", "Gaia The Fierce Knight", 7, "EARTH", "Warrior", 2300, 2100,
    "a purple-armoured lancer charging on a barded warhorse, twin lances lowered"),
  curseOfDragon: m("curseOfDragon", "Curse of Dragon", 5, "DARK", "Dragon", 2000, 1500,
    "a gaunt yellow wyvern wreathed in green necrotic flame"),
  summonedSkull: m("summonedSkull", "Summoned Skull", 6, "DARK", "Fiend", 2500, 1200,
    "a towering skeletal demon crackling with violet lightning"),
  busterBlader: m("busterBlader", "Buster Blader", 7, "EARTH", "Warrior", 2600, 2300,
    "a purple-armoured swordsman hefting an enormous notched greatsword",
    { atkPerFoeType: { type: "Dragon", atk: 500 } }),
  bigShieldGardna: m("bigShieldGardna", "Big Shield Gardna", 4, "EARTH", "Warrior", 100, 2600,
    "a kneeling guardian behind a vast ornate tower shield"),
  gazelle: m("gazelle", "Gazelle the King of Mythical Beasts", 4, "EARTH", "Beast", 1500, 1200,
    "a horned golden lion-beast mid-pounce"),
  berfomet: m("berfomet", "Berfomet", 4, "DARK", "Fiend", 1400, 1800,
    "a winged blue-skinned demon with a ram's skull crown"),
  magnetValkyrion: m("magnetValkyrion", "Berserk Gorilla", 4, "EARTH", "Beast", 2000, 1000,
    "a furious crimson-furred gorilla with iron knuckles", { mustAttack: true }),

  // -- Kaiba ------------------------------------------------------------
  blueEyes: m("blueEyes", "Blue-Eyes White Dragon", 8, "LIGHT", "Dragon", 3000, 2500,
    "a colossal white-scaled dragon with piercing blue eyes and jagged wings"),
  lordOfD: m("lordOfD", "Lord of D.", 4, "DARK", "Spellcaster", 1200, 1100,
    "a cloaked sorcerer in a dragon-skull helm", { protectsType: "Dragon" }),
  battleOx: m("battleOx", "Battle Ox", 4, "EARTH", "Beast-Warrior", 1700, 1000,
    "a hulking minotaur in blue armour swinging a broad axe"),
  saggi: m("saggi", "Saggi the Dark Clown", 3, "DARK", "Fiend", 600, 1500,
    "a spindly pale harlequin with a jagged grin, floating in shadow"),
  vorseRaider: m("vorseRaider", "Vorse Raider", 4, "DARK", "Beast-Warrior", 1900, 1200,
    "a horned blue-skinned warrior with a curved cleaver blade"),
  kaiserSeahorse: m("kaiserSeahorse", "Kaiser Sea Horse", 4, "LIGHT", "Sea Serpent", 1700, 1650,
    "an armoured cobalt seahorse knight with a trident", { doubleTributeFor: "LIGHT" }),
  laJinn: m("laJinn", "La Jinn the Mystical Genie of the Lamp", 4, "DARK", "Fiend", 1800, 1000,
    "a muscular green genie coiling out of a brass lamp"),
  rudeKaiser: m("rudeKaiser", "Rude Kaiser", 4, "EARTH", "Beast-Warrior", 1800, 1600,
    "a green reptilian warrior with twin battle-axes"),
  ryuKishin: m("ryuKishin", "Ryu-Kishin Powered", 4, "DARK", "Fiend", 1600, 1200,
    "a stone gargoyle glowing with unnatural power"),

  // -- Joey -------------------------------------------------------------
  redEyes: m("redEyes", "Red-Eyes Black Dragon", 7, "DARK", "Dragon", 2400, 2000,
    "a sleek obsidian dragon with blazing crimson eyes"),
  babyDragon: m("babyDragon", "Baby Dragon", 3, "WIND", "Dragon", 1200, 700,
    "a chubby amber hatchling dragon with oversized eyes"),
  timeWizard: m("timeWizard", "Time Wizard", 2, "WIND", "Spellcaster", 500, 400,
    "a tiny wizard clutching a clock-faced staff, gears spinning",
    { coinFlip: "timeRoulette" }),
  rocketWarrior: m("rocketWarrior", "Rocket Warrior", 4, "WIND", "Warrior", 1500, 1300,
    "a white armoured warrior shaped like a launch rocket", { pierceGuard: true }),
  pantherWarrior: m("pantherWarrior", "Panther Warrior", 4, "EARTH", "Beast-Warrior", 2000, 1600,
    "a black panther beastman in violet armour with a scimitar",
    { attackCost: "tribute" }),
  alligatorsSword: m("alligatorsSword", "Alligator's Sword", 4, "EARTH", "Beast-Warrior", 1500, 1200,
    "a bipedal crocodile swordsman in leather harness"),
  littleWinguard: m("littleWinguard", "Little-Winguard", 4, "WIND", "Warrior", 1400, 1800,
    "a small blue-caped guardian with a wing-crested helm"),
  gearfried: m("gearfried", "Gearfried the Iron Knight", 4, "EARTH", "Warrior", 1800, 1600,
    "a knight sealed inside living black iron armour"),
  axeRaider: m("axeRaider", "Axe Raider", 4, "EARTH", "Warrior", 1700, 1150,
    "a bare-chested warrior in orange armour hoisting a huge axe"),
  flameManipulator: m("flameManipulator", "Flame Manipulator", 3, "FIRE", "Spellcaster", 900, 1000,
    "a red-robed fire mage with a burning whip"),
  masaki: m("masaki", "Masaki the Legendary Swordsman", 4, "EARTH", "Warrior", 1100, 1100,
    "a grizzled ronin in blue robes drawing a katana"),

  // -- Mai --------------------------------------------------------------
  harpieLady: m("harpieLady", "Harpie Lady", 4, "WIND", "Winged Beast", 1300, 1400,
    "a winged woman with taloned feet, red hair and clawed gauntlets"),
  cyberHarpie: m("cyberHarpie", "Cyber Harpie Lady", 4, "WIND", "Winged Beast", 1800, 1300,
    "a harpy in gleaming cybernetic blue armour plating"),
  harpieSisters: m("harpieSisters", "Harpie Lady Sisters", 6, "WIND", "Winged Beast", 1950, 2100,
    "three winged harpy sisters in red, blue and green, wings spread in formation",
    { noNormalSummon: true }),
  harpiesPetDragon: m("harpiesPetDragon", "Harpie's Pet Dragon", 7, "WIND", "Dragon", 2000, 2500,
    "a rose-scaled dragon coiled protectively, wings flared",
    { atkPerAlly: { name: "Harpie Lady", atk: 300, def: 200 } }),
  harpieGirl: m("harpieGirl", "Harpie Girl", 2, "WIND", "Winged Beast", 500, 500,
    "a young harpy in training with small wings", { treatedAs: "Harpie Lady" }),
  amazonessSwordsWoman: m("amazonessSwordsWoman", "Amazoness Swords Woman", 4, "EARTH", "Warrior", 1500, 1600,
    "an amazon warrior in leopard hide with a heavy broadsword",
    { reflectBattleDamage: true }),
  dunames: m("dunames", "Dunames Dark Witch", 4, "LIGHT", "Fairy", 1800, 1050,
    "a winged fairy in white and gold armour"),
  birdface: m("birdface", "Birdface", 4, "WIND", "Winged Beast", 1600, 1600,
    "a hawk-headed sentinel in feathered plate"),

  // -- Tokens -----------------------------------------------------------
  sheepToken: m("sheepToken", "Sheep Token", 1, "EARTH", "Beast", 0, 0,
    "a small fluffy pastel-coloured cartoon sheep standing on a duel field",
    { token: true }),

  // -- Fusions ----------------------------------------------------------
  blueEyesUltimate: m("blueEyesUltimate", "Blue-Eyes Ultimate Dragon", 12, "LIGHT", "Dragon", 4500, 3800,
    "a three-headed colossal white dragon, all heads charging light",
    { fusion: ["blueEyes", "blueEyes", "blueEyes"] }),
  gaiaDragonChampion: m("gaiaDragonChampion", "Gaia the Dragon Champion", 7, "WIND", "Dragon", 2600, 2100,
    "a purple-armoured lancer riding a yellow wyvern through storm clouds",
    { fusion: ["gaia", "curseOfDragon"] }),
  chimera: m("chimera", "Chimera the Flying Mythical Beast", 6, "WIND", "Beast", 2100, 1800,
    "a winged two-headed lion-goat chimera",
    { fusion: ["gazelle", "berfomet"] }),
  flameSwordsman: m("flameSwordsman", "Flame Swordsman", 5, "FIRE", "Warrior", 1800, 1600,
    "a swordsman in red and blue armour whose blade is a column of fire",
    { fusion: ["flameManipulator", "masaki"] }),
  thousandDragon: m("thousandDragon", "Thousand Dragon", 7, "WIND", "Dragon", 2400, 2000,
    "an ancient wizened pink dragon with a long white beard",
    { fusion: ["babyDragon", "timeWizard"] }),
  blackSkullDragon: m("blackSkullDragon", "Black Skull Dragon", 9, "DARK", "Dragon", 3200, 2500,
    "a skeletal black dragon fused with a horned demon, breathing hellfire",
    { fusion: ["summonedSkull", "redEyes"] }),
};

export const FUSION_MONSTERS = Object.values(MONSTERS).filter((card) => card.fusion);
